server:
  port: 9090

spring:
  data:
    mongodb:
#      uri: mongodb://localhost:27017/netdisk
      host: 192.168.1.195
      port: 27017
      database: vnetdisk
      username: user1
      password: '123456'
      authentication-database: admin
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /vdownload/**
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
  web:
    resources:
      static-locations: file:/Users/star_wyx/Desktop/File



logging:
  config: classpath:logback-spring.xml
  file:
    path: /Users/star_wyx/coding/drive_springboot/log