server:
  port: 9090

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/netdisk
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB



logging:
  config: classpath:logback-spring.xml
  file:
    path: /Users/star_wyx/coding/drive_springboot/log
  level:
    org.springframework.data.mongodb.core.MongoTemplate: debug